name: 2021-07-06-pyhep-uproot-awkward-tutorial
channels:
  - conda-forge
dependencies:
  - pyarrow==4.0.1
  - numpy==1.20.3
  - matplotlib==3.4.2
  - pandas==1.2.4
  - hist==2.3.0
  - numba==0.53.1
  - xrootd==5.2.0
  - root==6.24.0
  - tbb-devel==2020.2
  - zstandard==0.15.2
  - lz4==3.1.3
  - python-xxhash==2.0.2
  - pip==21.1.2
  - pip:
      - awkward==1.4.0rc6
      - uproot==4.0.11
      - vector==0.8.3
      - particle==0.12.0
